### PR TITLE
feat(Likeable): Added extension of Rateable called 'Likeable' + Level AA accessiblity updates

### PR DESCRIPTION
**Pull request by SilbinaryWolf**
This is a major version update that changes how the underlying HTML/JS/CSS worked so that we could gain basic accessibility fixes.

- Added extension of Rateable called 'Likeable' that acts like a Facebook like button.
- Rewrote underlying HTML/CSS/JS to be Level AA accessible (can actualy tab over Stars now).
- Added the ability to change/remove rating.
- Now checks the validity of the score value sent.
- Can now enable ratings with a config variable (removes the 'EnableRatings' field if the config is set to true)

Since a lot of this changes are new and might have edges however, it might be a good idea to **wait approx. 2 weeks before accepting it** just so I can make any other big API changes if need be.

This update should also get a MAJOR version bump since the frontend stuff is changed a fair bit.

### CODE REVIEW

**Comment by sheadawson** [comment]
Awesome! If you can confirm in the next week or so that would be great as I'm going to be away/offline for 6 weeks from start of August. Otherwise happy to test/merge when I get back :)

**Comment by sheadawson** [comment]
Actually I will probably have to do it when I get back anyway because I have so much work to do before leaving. So sorry in advance for a likely delayed merge of this work!

**Comment by SilbinaryWolf** [comment]
Yup, no worries! Plenty of time for me to refactor and fix some things then :)

**Comment by sheadawson** [comment]
👍

**Comment by camfindlay** [comment]
Have also been thinking about a similar approach to the Likeable here. 

"Reviewable" allowing a user to leave a comment along with a 5 star rating, may look into this once this gets a merge in

**Comment by SilbinaryWolf** [comment]
@sheadawson This is all good to go in I'd say.

**Comment by sheadawson** [comment]
Merged! Feel free to add some information about the new features in the readme ;)

**Pull request merged**
